CREATE TABLE `onboarding_checklists` (
	`id` int AUTO_INCREMENT NOT NULL,
	`clientId` int NOT NULL,
	`paymentConfirmedStatus` enum('pending','done','skipped') NOT NULL DEFAULT 'pending',
	`paymentConfirmedAt` timestamp,
	`paymentConfirmedNote` text,
	`crmCreatedStatus` enum('pending','done','skipped') NOT NULL DEFAULT 'pending',
	`crmCreatedAt` timestamp,
	`welcomeEmailStatus` enum('pending','done','skipped') NOT NULL DEFAULT 'pending',
	`welcomeEmailSentAt` timestamp,
	`welcomeEmailContent` text,
	`formSentStatus` enum('pending','done','skipped') NOT NULL DEFAULT 'pending',
	`formSentAt` timestamp,
	`formToken` varchar(128),
	`formCompletedStatus` enum('pending','done','skipped') NOT NULL DEFAULT 'pending',
	`formCompletedAt` timestamp,
	`promptBuiltStatus` enum('pending','done','skipped') NOT NULL DEFAULT 'pending',
	`promptBuiltAt` timestamp,
	`savedPromptId` int,
	`vapiConfiguredStatus` enum('pending','done','skipped') NOT NULL DEFAULT 'pending',
	`vapiConfiguredAt` timestamp,
	`vapiAgentId` varchar(255),
	`testCallStatus` enum('pending','done','skipped') NOT NULL DEFAULT 'pending',
	`testCallAt` timestamp,
	`testCallNote` text,
	`clientLiveStatus` enum('pending','done','skipped') NOT NULL DEFAULT 'pending',
	`clientLiveAt` timestamp,
	`goLiveEmailContent` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `onboarding_checklists_id` PRIMARY KEY(`id`),
	CONSTRAINT `onboarding_checklists_clientId_unique` UNIQUE(`clientId`)
);
