CREATE TABLE `client_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`clientId` int NOT NULL,
	`tradingName` varchar(255),
	`abn` varchar(50),
	`phone` varchar(50),
	`address` varchar(512),
	`email` varchar(320),
	`website` varchar(512),
	`industryType` enum('plumber','electrician','carpenter','builder','gardener','painter','roofer','hvac','locksmith','pest_control','cleaner','lawyer','accountant','physio','dentist','health_clinic','real_estate','other'),
	`yearsInBusiness` int,
	`teamSize` int,
	`servicesOffered` json,
	`callOutFee` decimal(10,2),
	`hourlyRate` decimal(10,2),
	`minimumCharge` decimal(10,2),
	`afterHoursMultiplier` decimal(4,2),
	`serviceArea` text,
	`operatingHours` json,
	`emergencyAvailable` boolean DEFAULT false,
	`emergencyFee` decimal(10,2),
	`logoUrl` varchar(512),
	`primaryColor` varchar(16),
	`secondaryColor` varchar(16),
	`brandFont` enum('professional','modern','classic'),
	`tagline` varchar(255),
	`toneOfVoice` enum('professional','friendly','casual','formal'),
	`aiContext` text,
	`commonFaqs` json,
	`competitorNotes` text,
	`bookingInstructions` text,
	`escalationInstructions` text,
	`gstRate` decimal(5,2) DEFAULT '10.00',
	`paymentTerms` varchar(255),
	`validityDays` int DEFAULT 30,
	`defaultNotes` text,
	`onboardingCompleted` boolean NOT NULL DEFAULT false,
	`onboardingCompletedAt` timestamp,
	`onboardingStep` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `client_profiles_id` PRIMARY KEY(`id`),
	CONSTRAINT `client_profiles_clientId_unique` UNIQUE(`clientId`)
);
