CREATE TABLE `invoice_chases` (
	`id` varchar(36) NOT NULL,
	`clientId` int NOT NULL,
	`quoteId` varchar(36),
	`jobId` int,
	`invoiceNumber` varchar(32) NOT NULL,
	`customerName` varchar(255) NOT NULL,
	`customerEmail` varchar(320) NOT NULL,
	`customerPhone` varchar(50),
	`description` varchar(512),
	`amountDue` decimal(10,2) NOT NULL,
	`issuedAt` date NOT NULL,
	`dueDate` date NOT NULL,
	`status` enum('active','paid','snoozed','cancelled','escalated') NOT NULL DEFAULT 'active',
	`chaseCount` int NOT NULL DEFAULT 0,
	`lastChasedAt` timestamp,
	`nextChaseAt` timestamp,
	`snoozeUntil` timestamp,
	`paidAt` timestamp,
	`amountReceived` decimal(10,2),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `invoice_chases_id` PRIMARY KEY(`id`)
);
